#!/bin/bash

source venv/bin/activate

# args="--server.runOnSave true --logger.level debug"
# args="--server.runOnSave true --logger.level info --server.headless true --server.port 8601"
args="--server.runOnSave true --logger.level info --server.headless true"

export DEBUG=true
streamlit run $args run_streamlit.py
